name: CI/CD

on:
  pull_request:
    branches: [ master ]
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  backend_test:
    runs-on: self-hosted
    steps:
      - name: Tests ðŸš—
        run: |
            echo "Run tests"
  frontend_test:
    runs-on: self-hosted
    steps:
      - name: Tests ðŸš—
        run: |
            echo "Run tests"
  frontend_build:
    runs-on: self-hosted
    steps:
      - name: Tests ðŸš—
        run: |
            echo "Run tests"
  e2e_cypress:
    runs-on: self-hosted
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Tests ðŸš—
        run: |
            echo "Run tests"
